import{s as q,c as D,a as k,u as F,g as G,b as H,i as S,e as z}from"./CZQxHTy_.js";import{S as J,i as K,z as y,u as b,A as E,h as I,j as g,B as v,p as W,q as L,t as M,b as Q,C as R}from"./Cs1eCaUv.js";function j(l){return l?.length!==void 0?l:Array.from(l)}function w(l,e){const i={},o={},s={$$scope:1};let u=l.length;for(;u--;){const c=l[u],r=e[u];if(r){for(const f in c)f in r||(o[f]=1);for(const f in r)s[f]||(i[f]=r[f],s[f]=1);l[u]=r}else for(const f in c)s[f]=1}for(const c in o)c in i||(i[c]=void 0);return i}function Y(l){return typeof l=="object"&&l!==null?l:{}}/**
 * @license lucide-svelte v0.473.0 - ISC
 *
 * ISC License
 * 
 * Copyright (c) for portions of Lucide are held by Cole Bemis 2013-2022 as part of Feather (MIT). All other copyright (c) for Lucide are held by Lucide Contributors 2022.
 * 
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 * 
 */const C={xmlns:"http://www.w3.org/2000/svg",width:24,height:24,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor","stroke-width":2,"stroke-linecap":"round","stroke-linejoin":"round"};function A(l,e,i){const o=l.slice();return o[11]=e[i][0],o[12]=e[i][1],o}function N(l){let e,i=[l[12]],o={};for(let s=0;s<i.length;s+=1)o=k(o,i[s]);return{c(){e=y(l[11]),this.h()},l(s){e=E(s,l[11],{}),I(e).forEach(g),this.h()},h(){v(e,o)},m(s,u){W(s,e,u)},p(s,u){v(e,o=w(i,[u&32&&s[12]]))},d(s){s&&g(e)}}}function B(l){let e=l[11],i,o=l[11]&&N(l);return{c(){o&&o.c(),i=b()},l(s){o&&o.l(s),i=b()},m(s,u){o&&o.m(s,u),W(s,i,u)},p(s,u){s[11]?e?q(e,s[11])?(o.d(1),o=N(s),e=s[11],o.c(),o.m(i.parentNode,i)):o.p(s,u):(o=N(s),e=s[11],o.c(),o.m(i.parentNode,i)):e&&(o.d(1),o=null,e=s[11])},d(s){s&&g(i),o&&o.d(s)}}}function T(l){let e,i,o,s,u,c=j(l[5]),r=[];for(let t=0;t<c.length;t+=1)r[t]=B(A(l,c,t));const f=l[10].default,h=D(f,l,l[9],null);let _=[C,l[7],{width:l[2]},{height:l[2]},{stroke:l[1]},{"stroke-width":o=l[4]?Number(l[3])*24/Number(l[2]):l[3]},{class:s=l[6]("lucide-icon","lucide",l[0]?`lucide-${l[0]}`:"",l[8].class)}],d={};for(let t=0;t<_.length;t+=1)d=k(d,_[t]);return{c(){e=y("svg");for(let t=0;t<r.length;t+=1)r[t].c();i=b(),h&&h.c(),this.h()},l(t){e=E(t,"svg",{width:!0,height:!0,stroke:!0,"stroke-width":!0,class:!0});var a=I(e);for(let n=0;n<r.length;n+=1)r[n].l(a);i=b(),h&&h.l(a),a.forEach(g),this.h()},h(){v(e,d)},m(t,a){W(t,e,a);for(let n=0;n<r.length;n+=1)r[n]&&r[n].m(e,null);L(e,i),h&&h.m(e,null),u=!0},p(t,[a]){if(a&32){c=j(t[5]);let n;for(n=0;n<c.length;n+=1){const m=A(t,c,n);r[n]?r[n].p(m,a):(r[n]=B(m),r[n].c(),r[n].m(e,i))}for(;n<r.length;n+=1)r[n].d(1);r.length=c.length}h&&h.p&&(!u||a&512)&&F(h,f,t,t[9],u?H(f,t[9],a,null):G(t[9]),null),v(e,d=w(_,[C,a&128&&t[7],(!u||a&4)&&{width:t[2]},(!u||a&4)&&{height:t[2]},(!u||a&2)&&{stroke:t[1]},(!u||a&28&&o!==(o=t[4]?Number(t[3])*24/Number(t[2]):t[3]))&&{"stroke-width":o},(!u||a&257&&s!==(s=t[6]("lucide-icon","lucide",t[0]?`lucide-${t[0]}`:"",t[8].class)))&&{class:s}]))},i(t){u||(M(h,t),u=!0)},o(t){Q(h,t),u=!1},d(t){t&&g(e),R(r,t),h&&h.d(t)}}}function U(l,e,i){const o=["name","color","size","strokeWidth","absoluteStrokeWidth","iconNode"];let s=S(e,o),{$$slots:u={},$$scope:c}=e,{name:r=void 0}=e,{color:f="currentColor"}=e,{size:h=24}=e,{strokeWidth:_=2}=e,{absoluteStrokeWidth:d=!1}=e,{iconNode:t=[]}=e;const a=(...n)=>n.filter((m,O,P)=>!!m&&P.indexOf(m)===O).join(" ");return l.$$set=n=>{i(8,e=k(k({},e),z(n))),i(7,s=S(e,o)),"name"in n&&i(0,r=n.name),"color"in n&&i(1,f=n.color),"size"in n&&i(2,h=n.size),"strokeWidth"in n&&i(3,_=n.strokeWidth),"absoluteStrokeWidth"in n&&i(4,d=n.absoluteStrokeWidth),"iconNode"in n&&i(5,t=n.iconNode),"$$scope"in n&&i(9,c=n.$$scope)},e=z(e),[r,f,h,_,d,t,a,s,e,c,u]}class Z extends J{constructor(e){super(),K(this,e,U,T,q,{name:0,color:1,size:2,strokeWidth:3,absoluteStrokeWidth:4,iconNode:5})}}export{Z as I,Y as a,j as e,w as g};
